version: '3.6'

services:
  # DHCP compatible with glass https://github.com/Akkadius/glass-isc-dhcp/blob/master/docker-compose.yaml
  isc-dhcp:
    image: "networkboot/dhcpd"
    container_name: dhcp-server
    hostname: dhcp-server
    networks:
      external:
        ipv4_address: '${DHCP_SERVER_IP}'
    volumes:
    - ./dhcp/:/data/
    - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf

  # Create AMWA NMOS Testing container instance
  nmos-testing:
    image: amwa/nmos-testing:jtnm.aug2022-v1.0
    container_name: nmos-testing
    hostname: nmos-testing
    domainname: testsuite.nmos.tv
    entrypoint: |
       /bin/bash -c "/etc/init.d/dbus start;
       /etc/init.d/avahi-daemon start;
       python3 nmos-test.py & python3 nmos-testing-facade.py"
    ports:
    - "5000:5000"
    volumes:
    - "./UserConfig.py:/config/UserConfig.py"
    networks:
      external:
        ipv4_address: '${TEST_TOOL_IP}'

  # Just a utility for network troubleshooing
  busybox:
    image: busybox
    container_name: busybox
    entrypoint: |
        /bin/sh -c "tail -f /dev/null"
    networks:
      external:
        ipv4_address: '${BUSYBOX_IP}'

networks:
    external:
        # Create external macvlan subnet using host physical interface allowing containers to have their own IP addresses
        driver: macvlan
        driver_opts:
            parent: '${IFACE}'
        ipam:
            config:
            - subnet: '{SUBNET}'
