version: '3.6'

services:
  # DHCP compatible with glass https://github.com/Akkadius/glass-isc-dhcp/blob/master/docker-compose.yaml
  isc-dhcp:
    image: "networkboot/dhcpd"
    container_name: dhcp-server
    hostname: dhcp-server
    networks:
      external:
        ipv4_address: '192.168.6.101'
    volumes:
    - ./dhcp/:/data/
    - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf

  # Create NMOS Virtual Node container instance
  nmos-virtnode:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-virtnode
    hostname: nmos-virtnode
    domainname: testsuite.nmos.tv
    dns_search: testsuite.nmos.tv
    ports:
    - "80-81:80-81"
    volumes:
    - "./node/unicast_dsnsd.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    networks:
      external:
        ipv4_address: '192.168.6.102'
    dns:
      - '192.168.6.100'

networks:
    external:
        # Create external macvlan subnet using host physical interface allowing containers to have their own IP addresses
        driver: macvlan
        driver_opts:
            parent: eno2
        ipam:
            config:
            - subnet: 192.168.6.0/24
