version: '3.6'
services:

  # Create NMOS Registry/Controller container instance
  nmos-registry:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-registry
    hostname: nmos-registry
    domainname: local
    ports:
    - "80-81:80-81"
    - "1883:1883"
    volumes:
    - "./registry.json:/home/registry.json"
    environment:
    - RUN_NODE=FALSE
    network_mode: "host"
    #networks:
    #  external:
    #    ipv4_address: '192.168.6.101'

  # Create NMOS Virtual Node container instance
  nmos-virtnode:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-virtnode
    hostname: nmos-virtnode-ebulist
    domainname: nmos-testing.jt-nm.org
    dns_search: nmos-testing.jt-nm.org
    ports:
    - "8000-8100:8000-8100"
    volumes:
    - "./node_manual.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    network_mode: "host"
